version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sites:/sites
    ports:
      - "80:80"
      - "443:443"
